language: python
# python:
#   - "3.6"
branches:
  only:
    - master
    - dev
matrix:
  include:
    # Workaround for https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  # Runtime requirements
  - pip install -r requirements.txt
  # Test requirements
  - pip install -r test-requirements.txt
script:
  # Python validations
  - find . -name \*.py -exec pycodestyle {} +
  - find . -name \*.py -exec pydocstyle {} +
  - pylint opsy
