language: python
python:
  - "3.4"
  - "3.5"
branches:
  only:
    - master
    - dev
matrix:
  include:
    # Test javascript as part of python3.4 tests
    - language: node_js
      node_js: node
      install:
        - npm install -g grunt-cli
        - npm install
      script:
        - grunt
# command to install dependencies
install:
  # Runtime requirements
  - pip install -r requirements.txt
  # Test requirements
  - pip install -r test-requirements.txt
script:
  # Python validations
  - find . -name \*.py -exec pep8 {} +
  # Ignoring missing docstrings for now
  - find . -name \*.py -exec pep257 {} +
  - pylint opsy
