# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

workflows:
  version: 2
  main_workflow:
    jobs:
      - test_python36
      - test_python37
      - test_python38

jobs:
  test_python36:
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: opsy
          POSTGRES_DB: opsy
    working_directory: ~/repo
    steps:
      - common_setup:
          python_version: "3.6"
      - run_tests
  test_python37:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: opsy
          POSTGRES_DB: opsy
    working_directory: ~/repo
    steps:
      - common_setup:
          python_version: "3.7"
      - run_tests
  test_python38:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: opsy
          POSTGRES_DB: opsy
    working_directory: ~/repo
    steps:
      - common_setup:
          python_version: "3.8"
      - run_tests

commands:
  common_setup:
    description: Common steps for all jobs
    parameters:
      python_version:
          type: string
          default: ""
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-<< parameters.python_version >>-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            virtualenv ~/venv
            . ~/venv/bin/activate
            pip install tox
            tox --notest
      - save_cache:
          paths:
            - ~/repo/.tox
          key: v1-dependencies-<< parameters.python_version >>-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}

  run_tests:
    description: Run tests
    steps:
      - run:
          name: Run tests
          command: |
            . ~/venv/bin/activate
            tox
